spring:
  jpa:
    properties:
      hibernate:
        search:
          default: # <- This is the index name
            directory_provider: filesystem
            indexBase: /index-volume/demo-application
            indexmanager: directory-based # default